expert_data:
  shuffle: True
  train_fraction: !!float 0.7
  traj_limitation: -1
  batch_size: 1024

train:
  general:
    training_epochs: 2000
    seed: 2020
  generator:
    gamma: 0.995
    tau: 0.97
    clip_ratio: 0.1
    optim_step: 5
    mini_batch_size: -1
    sample_batch_size: 1024
  discriminator:
    optim_step: 1


policy:
  dim_state: 155
  dim_action: 6
  dim_hidden: 64
  activation: LeakyReLU
  dim_disc_action: 0
  action_log_std: 0.0
  disc_action_sections: !!python/tuple [0]
  use_multivariate_distribution: False
  learning_rate: !!float 3e-4


value:
  dim_state: 155
  dim_hidden: 64
  activation: LeakyReLU
  optim_value_iter: 1
  learning_rate: !!float 3e-4
  l2_reg: !!float 1e-3


discriminator:
  dim_state: 155
  dim_action: 6
  dim_hidden: 100
  activation: LeakyReLU
  learning_rate: !!float 3e-4
